CREATE DATABASE appRele;

use appRele;

CREATE TABLE CANAL (
	IDCA TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(8) NOT NULL
);

CREATE TABLE DISPOSITIVO (
    IDDIS INT(6) ZEROFILL UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    HOSTNAME VARCHAR(10) NOT NULL,
    IPADDR VARCHAR(16),
	PORTA VARCHAR(5),
    IDCA TINYINT UNSIGNED UNIQUE NOT NULL
);

CREATE TABLE USUARIO (
	IDUSR SMALLINT(6) ZEROFILL UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
	LOGIN VARCHAR(20) UNIQUE NOT NULL,
    SENHA CHAR(128) NOT NULL,
    IDGR TINYINT(3) ZEROFILL UNSIGNED NOT NULL,
	IDST TINYINT UNSIGNED NOT NULL
);

CREATE TABLE GRUPO (
    IDGR TINYINT(3) ZEROFILL UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(15) NOT NULL
);

CREATE TABLE STUSR (
    IDST TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(14) NOT NULL
);

CREATE TABLE AUDITORIA (
	IDLOG BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ACAO VARCHAR(20) NOT NULL,
    IDUSR SMALLINT(6) ZEROFILL UNSIGNED NOT NULL,
    IDDIS INT(6) ZEROFILL UNSIGNED NOT NULL,
	DTREG DATETIME
);
 
ALTER TABLE DISPOSITIVO ADD CONSTRAINT FK_DISP FOREIGN KEY (IDCA) REFERENCES CANAL (IDCA) ON DELETE RESTRICT;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_GRUPO FOREIGN KEY (IDGR) REFERENCES GRUPO (IDGR) ON DELETE RESTRICT;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_STUSR FOREIGN KEY (IDST) REFERENCES STUSR (IDST) ON DELETE RESTRICT;
ALTER TABLE AUDITORIA ADD CONSTRAINT FK_AUDITORIA_USUARIO FOREIGN KEY (IDUSR) REFERENCES USUARIO (IDUSR) ON DELETE RESTRICT;
ALTER TABLE AUDITORIA ADD CONSTRAINT FK_AUDITORIA_DISPOSITIVO FOREIGN KEY (IDDIS) REFERENCES DISPOSITIVO (IDDIS) ON DELETE RESTRICT;

INSERT INTO CANAL (DESCRICAO) VALUES ('CANAL 1'), ('CANAL 2'), ('CANAL 3');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Administradores'), ('Usuários');
INSERT INTO STUSR (DESCRICAO) VALUES ('Habilitado'), ('Desabilitado');
INSERT INTO USUARIO (NOME, LOGIN, SENHA, IDGR, IDST) VALUES ('	', 'Admin', SHA2('admin', 512), 1, 1);

CREATE VIEW INFOUSR AS
	SELECT 
		U.IDUSR AS ID, U.NOME, U.LOGIN, G.DESCRICAO AS GRUPO, S.DESCRICAO AS STATUS
	FROM 
		USUARIO AS U
	INNER JOIN
		GRUPO G ON G.IDGR = U.IDGR
	INNER JOIN
		STUSR S ON S.IDST = U.IDST
	ORDER BY
		U.IDUSR;

CREATE VIEW INFODISP AS
	SELECT 
		D.IDDIS AS ID, D.HOSTNAME, D.IPADDR AS IP, D.PORTA, C.IDCA AS CANAL
	FROM 
		DISPOSITIVO D
	INNER JOIN 
		CANAL C ON C.IDCA = D.IDCA
	ORDER BY
		D.IDDIS;
	

GRANT ALL PRIVILEGES ON appRele.* TO 'rele'@'localhost';
CREATE USER 'rele'@'localhost' IDENTIFIED BY '';
